#!/usr/bin/env python3
"""Flatten "Farhan Jamil" (Snell Roundhand Bold) into one SVG path -> glyphs.py.

Only needed if the wording or the face changes; `build.py` reads the generated
glyphs.py. Requires macOS' Snell Roundhand and `pip install fonttools`.

    python3 tools/signature/extract.py
"""

import os

from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTCollection

FONT = "/System/Library/Fonts/Supplemental/SnellRoundhand.ttc"
FACE = 1  # 0 regular, 1 bold, 2 black
TEXT = "Farhan Jamil"

font = TTCollection(FONT).fonts[FACE]
cmap = font.getBestCmap()
glyph_set = font.getGlyphSet()
hmtx = font["hmtx"]
upem = font["head"].unitsPerEm

kern = {}
for table in font["kern"].kernTables:
    kern.update(table.kernTable)

names = [cmap.get(ord(c)) for c in TEXT]

# lay the string out along the baseline, applying pair kerning
placed, x = [], 0.0
for i, name in enumerate(names):
    if name is None:
        x += upem * 0.25
        continue
    if i and names[i - 1]:
        x += kern.get((names[i - 1], name), 0)
    placed.append((name, x))
    x += hmtx[name][0]

bounds = BoundsPen(glyph_set)
for name, gx in placed:
    glyph_set[name].draw(TransformPen(bounds, Transform(1, 0, 0, 1, gx, 0)))
xmin, ymin, xmax, ymax = bounds.bounds

# ...and flip to SVG's y-down space, baseline still at y=0
pen = SVGPathPen(glyph_set, ntos=lambda v: f"{round(v)}")
for name, gx in placed:
    glyph_set[name].draw(TransformPen(pen, Transform(1, 0, 0, -1, gx, 0)))

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "glyphs.py")
with open(out, "w") as f:
    f.write(
        f'"""Generated by extract.py — {TEXT}, {font["name"].getDebugName(4)}, '
        f'{upem} units/em, y-down with the baseline at y=0. Do not edit."""\n\n'
        f"GLYPH_BOUNDS = ({round(xmin)}, {round(-ymax)}, {round(xmax)}, {round(-ymin)})\n\n"
        f'GLYPH_PATH = "{pen.getCommands()}"\n'
    )
print(f"wrote {out}: {len(placed)} glyphs, bounds {(round(xmin), round(-ymax), round(xmax), round(-ymin))}")
